routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CarsController@index')->middleware('auth');

Route::prefix('cars')->name('cars.')->middleware('auth')->group(function () {
    Route::get('/', 'CarsController@index')->name('index');
    Route::get('/create', 'CarsController@create')->name('create');
    Route::get('{id}', 'CarsController@show')->name('show');
    Route::get('{id}/edit', 'CarsController@edit')->name('edit');
    Route::put('{id}', 'CarsController@update')->name('update');
    Route::post('/', 'CarsController@store')->name('store');
    Route::delete('{id}', 'CarsController@destroy')->name('destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/auth/github/login', 'Auth\\LoginController@redirectToGithub');
Route::any('/auth/github/callback', 'Auth\\LoginController@handleGithubProviderCallback');

app/Http/Controllers/Api/CarsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Entity\Car;
use App\Http\Controllers\Controller;
use App\Http\Requests\CarRequest;
use Illuminate\Auth\Access\AuthorizationException;

class CarsController extends Controller
{
    /**
     * @return \Illuminate\Database\Eloquent\Collection|static[]
     */
    public function index()
    {
        return Car::all();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        $car = Car::findOrFail($id);

        return $car;
    }

    /**
     * @param $id
     * @param CarRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, CarRequest $request)
    {
        $car = Car::findOrFail($id);

        try {
            $this->authorize('update', $car);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        $car->update($request->all());

        return $car;
    }

    /**
     * @param CarRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CarRequest $request)
    {
        try {
            $this->authorize('create', Car::class);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        $car = Car::create($request->all());

        return $car;
    }

    /**
     * @param $id
     * @return array|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $car = Car::findOrFail($id);

        try {
            $this->authorize('delete', $car);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        $car->delete();

        return ['success' => true];
    }
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Car;
use App\Http\Requests\CarRequest;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;

class CarsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('cars.index', ['cars' => Car::all()]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        try {
            $this->authorize('create', Car::class);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        return view('cars.create', ['car' => (new Car([
            'color' => null,
            'model' => null,
            'registration_number' => null,
            'year' => null,
            'mileage' => null,
            'price' => null,
            'user_id' => null,
        ]))->toArray()]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $car = Car::findOrFail($id);

        return view("cars.show", ['car' => $car->toArray()]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $car = Car::findOrFail($id);

        try {
            $this->authorize('update', $car);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        return view("cars.edit", ['car' => $car->toArray()]);
    }

    /**
     * @param $id
     * @param CarRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function update($id, CarRequest $request)
    {
        $car = Car::findOrFail($id);

        try {
            $this->authorize('update', $car);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        $car->update($request->all());

        return $this->show($id);
    }

    /**
     * @param CarRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function store(CarRequest $request)
    {
        try {
            $this->authorize('create', Car::class);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        Car::create($request->all());

        return $this->index();
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function destroy($id, Request $request)
    {
        $car = Car::findOrFail($id);

        try {
            $this->authorize('delete', $car);
        } catch (AuthorizationException $e) {
            return redirect('/');
        }

        $car->delete();

        return redirect()->route('cars.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('cars.index');
    }
}

resources/views/cars/_form.blade.php
{!! csrf_field() !!}

<div class="form-group @if ($errors->has('model')) has-error @endif">
    <label for="model">Model</label>
    <input value="{{ old('model') ?? $car['model'] }}" type="text" class="form-control" name="model" id="model" placeholder="Model">

    @if ($errors->has('model'))
        <span class="help-block">{{ $errors->first('model') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('registration_number')) has-error @endif">
    <label for="registration_number">Registration Number</label>
    <input value="{{ old('registration_number') ?? $car['registration_number'] }}" type="text" class="form-control" name="registration_number" id="registration_number" placeholder="Registration Number">

    @if ($errors->has('registration_number'))
        <span class="help-block">{{ $errors->first('registration_number') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('year')) has-error @endif">
    <label for="year">Year</label>
    <input value="{{ old('year') ?? $car['year'] }}" type="text" class="form-control" name="year" id="year" placeholder="Year">

    @if ($errors->has('year'))
        <span class="help-block">{{ $errors->first('year') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('color')) has-error @endif">
    <label for="color">Color</label>
    <input value="{{ old('color') ?? $car['color'] }}" type="text" class="form-control" name="color" id="color" placeholder="Color">

    @if ($errors->has('color'))
        <span class="help-block">{{ $errors->first('color') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('price')) has-error @endif">
    <label for="price">Price</label>
    <input value="{{ old('price') ?? $car['price'] }}" type="text" class="form-control" name="price" id="price" placeholder="Price">

    @if ($errors->has('price'))
        <span class="help-block">{{ $errors->first('price') }}</span>
    @endif
</div>

<button type="submit" class="btn btn-default">Save</button>

resources/views/cars/create.blade.php
@extends('layouts.app')

@section('content')
    <h2>{{ $car['model'] }}</h2>

    <form action="{{ route('cars.store') }}" method="POST">
        @include('cars._form', compact('car'))
    </form>
@endsection

resources/views/cars/edit.blade.php
@extends('layouts.app')

@section('content')
    <h2>{{ $car['model'] }}</h2>

    <form action="{{ route('cars.update', $car['id']) }}" method="POST">
        {{ method_field('PUT') }}

        @include('cars._form', compact('car'))
    </form>
@endsection

resources/views/cars/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="list-group">
        @forelse($cars as $car)
            <a class="list-group-item" href="{{ route('cars.show', $car['id']) }}">
                {{ $car['model'] }} [{{ $car['color'] }}] — ${{ $car['price'] }}
            </a>
        @empty
            <p class="list-group-item">No cars</p>
        @endforelse
    </div>
@endsection

resources/views/cars/show.blade.php
@extends('layouts.app')

@section('content')
    <h2>{{ $car['model'] }}</h2>
    <p><strong>Year</strong>: {{ $car['year'] }}</p>
    <p><strong>Registration number</strong>: {{ $car['registration_number'] }}</p>
    <p><strong>Color</strong>: {{ $car['color'] }}</p>
    <p><strong>Price</strong>: ${{ $car['price'] }}</p>

    @can('update', new \App\Entity\Car($car))
        <a href="{{ route('cars.edit', $car['id']) }}" class="btn btn-default edit-button" style="display: inline-block">Edit</a>
    @endcan

    @can('delete', new \App\Entity\Car($car))
        <form action="{{ route('cars.destroy', $car['id']) }}" method="POST" style="display: inline-block">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <button type="submit" class="btn btn-danger delete-button">Delete</button>
        </form>
    @endcan
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Best Car Hire Deals
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    @if (!Auth::guest())
                        <!-- Left Side Of Navbar -->
                        <ul class="nav navbar-nav">
                            <li class="@if (request()->url() === route('cars.index') || request()->path() === '/') active @endif">
                                <a href="{{ route('cars.index') }}">Cars list</a>
                            </li>
                            @can('create', \App\Entity\Car::class)
                                <li class="@if (request()->url() === route('cars.create')) active @endif">
                                    <a href="{{ route('cars.create') }}">Add</a>
                                </li>
                            @endcan
                        </ul>
                    @endif

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->first_name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? 'Cars' }}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand">Cars Service</a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="@if (request()->url() === route('cars.index')) active @endif">
                        <a href="{{ route('cars.index') }}">Cars list</a>
                    </li>
                    <li class="@if (request()->url() === route('cars.create')) active @endif">
                        <a href="{{ route('cars.create') }}">Add</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @yield('content')
    </div>
</body>
</html>